apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: prueba-prueba
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: Juanlu1411
